### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by mafrahim** [sudo97/Roku-IPTV#1]
hey I tried it earlier and just got blank screen.

**Comment by mafrahim** [comment]
have to use HTTP only :). thanks :+1:

**Comment by sudo97** [comment]
Sorry for no response, was too busy, glad you've worked it out

**Comment by mafrahim** [comment]
yes thanks. do you think we can map FFW and Rew buttons to move up and down in the channel list without exiting the full screen?
https://github.com/sudo97/Roku-IPTV/blob/master/components/MainScene.brs#L20

**Comment by sudo97** [comment]
Might be good, we could just leave the focus on the list when we set video
to fullscreen, so when user presses ffd or rew -- the list would handle
these keys, or we could implement it by ourselves using jumptToItem field
of the list

24 июля 2017 г. 15:22 пользователь "mafrahim" <notifications@github.com>
написал:
