### ISSUE TITLE
Channels Guide

### ISSUE THREAD

**Issue by fabdelgado** [sudo97/Roku-IPTV#5]
I have a m3u list that contains the show tv name in addition to the name of the channel. Is it possible to show it through a modification?

**Comment by sudo97** [comment]
Yes, but you have to change the parser, which is not a piece of cake

**Comment by fabdelgado** [comment]
Thanks!

**Comment by sudo97** [comment]
Could you provide the example?

пт, 27 июля 2018 г., 0:24 Fabián Delgado <notifications@github.com>:

**Comment by fabdelgado** [comment]
Yes, sure. I will create a frontend like this https://developer.roku.com/en-gb/publish but using categories instead of channels.

**Comment by sudo97** [comment]
what is this?
